language: go
go:
- 1.7.x
notifications:
  email: false
install:
- true
script:
- "./script/build"
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: hyenPy4ZbPy3n2omr2P4/d4XZyibqC5WvngZ0l9lEZioaTbBk9eseNuf/L77RVuLs0J6vjG7XNW7YQlQumhcbP/D8uWPSV9OtKebEXWoMhMM9oZ6t76oIatOoPkSc4vmRqbvpi6Nbx8KGgzge8XIY8bFdIej+FEqfxSo9zYrEf+OCa/0eiF2KMdf/rvyU+2gvOlAWr4dIpSgFqzE6zjVCHoGrYwjNIKxhiR0Vv7dL5pkYJxjPv6zOx90CXCx4A+YQVxBY+GVcUNJ8A8SMsC/LpoeK/BvYJYRUfMwL47u/Skka2i20CM3aewYMoJhTSwrFefeNX0r36Fu32n0XZqS9/gU+34B96kPJ/HgxGbQb4Ydperl7a4CgvXhOSIMkfuB+unhHRS3FgCqTOrPZAK/Cd6Wt1Y9QOuPEPW64VfC+jF8MGrCEvemBInj9XapHUYxv4ABjGdd+sg2azE0VIk5gOBvQX3hGKBNqrvs+2EYkBjmr8LO31aiekeKKLTRlzFK8SXkuPkP9w8xPOLXWZwo2Kr3ShcSeFhlXTyui+SPtVgwH8X4JnEVUTQLZ1afR15fl9nABJhCwJwx9wiwUpZ6FVAVtJTKPzhjkFPKaQisJk7BFa2REbkZ36ecaC0h1ElaYM8rAHhw8QMZznQxMVYzTLzSFAOB3gXC1KXBZ8ysF/k=
  file:
    - static-pod-validate.linux
    - static-pod-validate.darwin
  on:
    repo: bakins/static-pod-validate
    tags: true
